variables:
  default: 
    global:
      backend: local
  openshift:
    global:
      backend: kubernetes
      
blueprint:
  openshift:
    global:
      resourceManager:
        kubernetes:
          cpuUnitsPerCore: 1.0
        config:
          walltime: 14400.0
          backend: kubernetes

  openshift:
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

components:
- name: hi
  stage: 0
  command:
    executable: "bin/run.py"
  resourceManager:
    config:
      backend: "%(backend)s"
    kubernetes:
      # if you're just using python, you can use the base image of the st4sd orchestrator
      # so that you don't have to think about creating imagePullSecrets etc
      # quay.io/st4sd/official-base/st4sd-runtime-core
      image: quay.io/st4sd/official-base/st4sd-runtime-core
platforms:
  - openshift

version: 1.0.0
