variables:
  default: 
    global:
      backend: local
  openshift:
    global:
      backend: kubernetes
      
blueprint:
  openshift:
    global:
      resourceManager:
        kubernetes:
          cpuUnitsPerCore: 1.0
        config:
          walltime: 14400.0
          backend: kubernetes

  openshift:
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

components:
- name: hi
  stage: 0
  command:
    executable: "bin/run.py"
  resourceManager:
      config:
        backend: local
platforms:
  - default
  - openshift

version: 1.0.0
